### ISSUE TITLE
Error explore app

### ISSUE THREAD

**Issue by rini1010** [aldebaran/naoqi_navigation_samples#27]
Hello, I just downloaded the navigation samples, but I'm getting an error:

[ERROR] behavior.box :_safeCallOfUserMethod:125 _Behavior__lastUploadedChoregrapheBehaviorexplore_display1362608160:/Get map_1: Traceback (most recent call last):   File "/opt/aldebaran/lib/python2.7/site-packages/albehavior.py", line 115, in _safeCallOfUserMethod     func()   File "<string>", line 21, in onInput_onStart   File "/opt/aldebaran/lib/python2.7/site-packages/naoqi.py", line 194, in __call__     return self.__wrapped__.method_missing(self.__method__, *args, **kwargs)   File "/opt/aldebaran/lib/python2.7/site-packages/naoqi.py", line 264, in method_missing     raise e RuntimeError: 	ALNavigation::getMetricalMap 	No exploration loaded.

What do I have to do? What exploration do I have to load?
Thank you for your help!

**Comment by scarlettfres** [comment]
Hi! 
When is this error happening? Usually it means you are trying to get a map but the robot do not have a loaded one.

Maybe you are trying to use patrol? 
In that case, after making maps with the explore app, you need to use the app "places" to load a map (and [optional] add points of interest in it).
Tell me if it helps!

**Comment by FLLTT** [comment]
When I initially cloned this code, I encountered a similar issue. Can you provide guidance on how to address it?
